# Generated by Django 5.0.2 on 2024-02-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.CharField(max_length=255)),
                ('proposal_key', models.CharField(max_length=255)),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('group', models.IntegerField(default=None, null=True)),
                ('collection', models.IntegerField(default=None, null=True)),
                ('research_plan', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
