# Generated by Django 5.1.1 on 2024-09-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='report',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='technology',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('date', 'proposal_id', 'technology')},
        ),
    ]
