# Generated by Django 5.0.6 on 2024-06-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='proposal_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
