# Generated by Django 5.1.1 on 2024-10-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_alter_report_unique_together_report_synced_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='proposal_id',
        ),
    ]
