# Generated by Django 5.1.7 on 2025-03-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_remove_proposal_proposal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='research_plan_status_table',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
